/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "ShellExecXcodeTimeout"

val shellexec = file("../ShellExec")
if (shellexec.exists()) {
    // Composite build
    includeBuild(shellexec) {
        dependencySubstitution {
            substitute(module("at.phatbl:shellexec")).with(project(":"))
        }
    }
}

pluginManagement {
    resolutionStrategy {
        eachPlugin {
            when (requested.id.id) {
                "at.phatbl.shellexec" -> useModule("at.phatbl:shellexec:${requested.version}")
                else -> Unit
            }
        }
    }
}
